/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  causal_discover: () => import("@/views/causal/discover/index.vue"),
  causal_effect: () => import("@/views/causal/effect/index.vue"),
  file: () => import("@/views/file/index.vue"),
  home: () => import("@/views/home/index.vue"),
  permission_apply: () => import("@/views/permission/apply/index.vue"),
  permission_manage: () => import("@/views/permission/manage/index.vue"),
  permission_my: () => import("@/views/permission/my/index.vue"),
  scene_create: () => import("@/views/scene/create/[id].vue"),
  scene_home: () => import("@/views/scene/home/index.vue"),
  scene_list: () => import("@/views/scene/list/index.vue"),
  task_create: () => import("@/views/task/create/[id].vue"),
  task_home: () => import("@/views/task/home/index.vue"),
  task_list: () => import("@/views/task/list/index.vue"),
  taskchain_create: () => import("@/views/taskChain/create/index.vue"),
  taskchain_list: () => import("@/views/taskChain/list/index.vue"),
  taskunit_create: () => import("@/views/taskUnit/create/index.vue"),
  taskunit_list: () => import("@/views/taskUnit/list/index.vue"),
  visualization: () => import("@/views/visualization/index.vue"),
};
