/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'file',
    path: '/file',
    component: 'layout.base$view.file',
    meta: {
      title: 'file',
      i18nKey: 'route.file',
      requiredPermission: 'file'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|register)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'permission',
    path: '/permission',
    component: 'layout.base',
    meta: {
      title: 'permission',
      i18nKey: 'route.permission'
    },
    children: [
      {
        name: 'permission_apply',
        path: '/permission/apply',
        component: 'view.permission_apply',
        meta: {
          title: 'permission_apply',
          i18nKey: 'route.permission_apply'
        }
      },
      {
        name: 'permission_manage',
        path: '/permission/manage',
        component: 'view.permission_manage',
        meta: {
          title: 'permission_manage',
          i18nKey: 'route.permission_manage'
        }
      },
      {
        name: 'permission_my',
        path: '/permission/my',
        component: 'view.permission_my',
        meta: {
          title: 'permission_my',
          i18nKey: 'route.permission_my'
        }
      }
    ]
  },
  {
    name: 'task',
    path: '/task',
    component: 'layout.base',
    meta: {
      title: 'task',
      i18nKey: 'route.task',
      localIcon: 'task'
    },
    children: [
      {
        name: 'task_create',
        path: '/task/create/:id',
        component: 'view.task_create',
        meta: {
          title: 'task_create',
          i18nKey: 'route.task_create',
          hideInMenu: true,
          requiredPermission: 'task'
        }
      },
      {
        name: 'task_home',
        path: '/task/home',
        component: 'view.task_home',
        meta: {
          title: 'task_home',
          i18nKey: 'route.task_home',
          localIcon: 'task_create',
          requiredPermission: 'task'
        }
      },
      {
        name: 'task_list',
        path: '/task/list',
        component: 'view.task_list',
        meta: {
          title: 'task_list',
          i18nKey: 'route.task_list',
          localIcon: 'task_list',
          requiredPermission: 'task'
        }
      }
    ]
  },
  {
    name: 'taskchain',
    path: '/taskchain',
    component: 'layout.base',
    meta: {
      title: 'taskchain',
      i18nKey: 'route.taskchain',
      localIcon: 'task_chains'
    },
    children: [
      {
        name: 'taskchain_create',
        path: '/taskchain/create',
        component: 'view.taskchain_create',
        meta: {
          title: 'taskchain_create',
          i18nKey: 'route.taskchain_create',
          localIcon: 'task_chains_create'
        }
      },
      {
        name: 'taskchain_list',
        path: '/taskchain/list',
        component: 'view.taskchain_list',
        meta: {
          title: 'taskchain_list',
          i18nKey: 'route.taskchain_list',
          localIcon: 'task_chains'
        }
      }
    ]
  },
  {
    name: 'taskunit',
    path: '/taskunit',
    component: 'layout.base',
    meta: {
      title: 'taskunit',
      i18nKey: 'route.taskunit',
      localIcon: 'task'
    },
    children: [
      {
        name: 'taskunit_create',
        path: '/taskunit/create',
        component: 'view.taskunit_create',
        meta: {
          title: 'taskunit_create',
          i18nKey: 'route.taskunit_create',
          localIcon: 'task_create'
        }
      },
      {
        name: 'taskunit_list',
        path: '/taskunit/list',
        component: 'view.taskunit_list',
        meta: {
          title: 'taskunit_list',
          i18nKey: 'route.taskunit_list',
          localIcon: 'task_list'
        }
      }
    ]
  },
  {
    name: 'visualization',
    path: '/visualization',
    component: 'layout.base$view.visualization',
    meta: {
      title: 'visualization',
      i18nKey: 'route.visualization',
      icon: 'mdi:chart-areaspline',
      requiredPermission: 'scene'
    }
  }
];
